version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Using Node.js 18. You can change to 20 if preferred.
    commands:
      # Step 1: Change into the React application's directory.
      # This is where your package.json, src/, public/ are located.
      - echo "Changing working directory to 'examples/demo-app/'"
      - cd examples/demo-app/
      - echo "Current working directory: $(pwd)"

      # Step 2: Install Node.js dependencies for the React app.
      # This command looks for package.json in the current directory ('examples/demo-app/').
      - echo "Installing npm dependencies for React app..."
      - npm install

  build:
    commands:
      # Step 3: Build the React application.
      # This creates the optimized static assets in a 'build/' folder
      # inside 'examples/demo-app/'.
      - echo "Building React application..."
      - npm run build

      # Step 4: Copy appspec.yml and scripts/ into the React app's 'build' output.
      # CodeDeploy expects appspec.yml and scripts at the root of the artifact.
      # Since we are currently in 'examples/demo-app/', we go up one level (..) to 'examples/'
      # to find appspec.yml and scripts/.
      - echo "Copying appspec.yml and scripts to the React build output directory..."
      - cp ../appspec.yml build/
      - cp -r ../scripts/ build/

      # Step 5: Verify the contents of the 'build/' directory.
      # This helps debug if files aren't showing up as expected in the artifact.
      - echo "Contents of the final artifact directory (React app build/ + appspec/scripts):"
      - ls -la build/
      - ls -la build/scripts/

artifacts:
  files:
    - '**/*' # Include all files and subdirectories from the base-directory.
  discard-paths: no
  # CRITICAL: This sets the root of your deployment artifact.
  # The 'build/' folder generated by React (now containing appspec and scripts)
  # inside 'examples/demo-app/' will be the root of the artifact.
  base-directory: examples/demo-app/build
