version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Using Node.js 18, a common LTS version. You can change to 20 if preferred.
    commands:
      # Step 1: Change into the React application directory.
      # Remember, the buildspec.yml itself is in 'examples/',
      # but the React app is in 'examples/my-react-app/'.
      - echo "Changing working directory to 'examples/demo-app/'"
      - cd examples/demo-app/
      - echo "Current working directory: $(pwd)"

      # Step 2: Install Node.js dependencies for the React app.
      # This looks for package.json in 'examples/my-react-app/' (current directory).
      - echo "Installing npm dependencies for React app..."
      - npm install

  build:
    commands:
      # Step 3: Build the React application.
      # This command (npm run build) will create a 'build/' folder
      # inside 'examples/my-react-app/' containing the optimized static assets.
      - echo "Building React application..."
      - npm run build

      # Step 4: Now, copy appspec.yml and scripts/ into the React app's 'build' output.
      # CodeDeploy expects appspec.yml and scripts to be at the root of the artifact.
      # Since we are currently in 'examples/my-react-app/', we need to go up one level to 'examples/'
      # to find appspec.yml and scripts/.
      - echo "Copying appspec.yml and scripts to the React build output directory..."
      - cp ../appspec.yml build/
      - cp -r ../scripts/ build/

      # Step 5: Verify the contents of the 'build/' directory (which will become the artifact root).
      - echo "Contents of the final artifact directory (React app build/ + appspec/scripts):"
      - ls -la build/
      - ls -la build/scripts/ # Check if scripts directory is inside build/

artifacts:
  files:
    - '**/*' # Include all files and subdirectories from the base-directory.
  discard-paths: no
  # CRITICAL: This sets the root of your deployment artifact.
  # The 'build/' folder generated by React (now containing appspec and scripts)
  # inside 'examples/my-react-app/' will be the root of the artifact.
  base-directory: examples/demo-app/build
