name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
